# Site settings
language:               "es"
title:                  "borders-collies"
description:            "Toda la informacion que necesitas sobre la cria, el adiestramiento y los cuidados del Border Collie."
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"
  - "/assets/"

exclude:
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/:title/"
paginate_path:    "/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]
